apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: node-exporter-auto-update
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux-bot@pi4.com
        name: Flux Image Update Bot
      messageTemplate: |
        [automated] Update node-exporter image

        Bumped images:
        {{range .Updated.Images}}
        - {{println .}}
        {{end}}
    push:
      branch: master
  update:
    path: "./"
    strategy: Setters
