apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: vm
spec:
  releaseName: node-exporter
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "4.42.0"
  interval: 1m
  timeout: 5m
  dependsOn:
    - name: prometheus-operator-crds
      namespace: vm
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      # Маркер для автооновлення - FluxCD замінить цей тег автоматично
      tag: "v1.9.1" 
    nodeSelector:
      kubernetes.io/hostname: server
