apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      targetPort: 8080
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
