apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx