apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: demo
  namespace: vm
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/instance: demo
spec:
  # Налаштування Service
  serviceSpec:
    type: ClusterIP
    ports:
      - name: http
        port: 8429
        targetPort: 8429
        protocol: TCP
  
  # Налаштування Ingress для UI
  ingressSpec:
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    rules:
      - host: vmagent.pi4.local  # Змініть на ваш домен
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: vmagent-demo
                  port:
                    number: 8429
  
  # Налаштування ресурсів
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 512Mi
  
  # Налаштування storage
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: "1Gi"
        # storageClassName: "fast-ssd"
  
  # Налаштування реплік
  replicaCount: 1
  
  # Налаштування remoteWrite
  remoteWrite:
    - url: "http://vmcluster-demo-vminsert:8480/insert/0/prometheus/api/v1/write"
  
  # Налаштування scrape configs
  serviceScrapeSpec:
    selector:
      matchLabels:
        app.kubernetes.io/name: vmcluster
    endpoints:
      - port: vmselect
        interval: 30s
        path: /metrics
