apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: dev
  namespace: vm
  labels:
    app.kubernetes.io/name: vmcluster
    app.kubernetes.io/instance: dev
spec:
  retentionPeriod: "30d"
  # Renovate буде відстежувати цю версію та пропонувати оновлення
  clusterVersion: v1.107.0-cluster
  replicationFactor: 1
  
  vmstorage:
    replicaCount: 1
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "10Gi"
          # storageClassName: "fast-ssd"
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    nodeSelector:
      kubernetes.io/hostname: server
  
  vmselect:
    replicaCount: 1
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "5Gi"
          # storageClassName: "fast-ssd"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 1Gi
    nodeSelector:
      kubernetes.io/hostname: server
  
  vminsert:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeSelector:
      kubernetes.io/hostname: server