apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
spec:
  releaseName: zigbee2mqtt
  chart:
    spec:
      chart: zigbee2mqtt
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
      version: "2.6.1"
  interval: 1m
  values:
    statefulset:
      nodeSelector:
        kubernetes.io/hostname: pi4
      securityContext:
        privileged: true
      volumes:
        - name: zigbee
          hostPath:
            path: /dev/ttyUSB0
            type: CharDevice
      volumeMounts:
        - name: zigbee
          mountPath: /dev/ttyUSB0
    config:
      homeassistant: true
      mqtt:
        server: "mqtt://mosquitto.home-assistant.svc.cluster.local:1883"
        user: ""
        password: ""
      serial:
        port: "/dev/ttyUSB0"
        adapter: "ember"
