# Встановлення CRDs через HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.18.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  # Встановлюємо тільки CRDs, без основних компонентів
  values:
    installCRDs: true
    # Відключаємо всі інші компоненти, залишаємо тільки CRDs
    webhook:
      enabled: false
    cainjector:
      enabled: false
    controller:
      enabled: false
  # Важливо: цей HelmRelease має бути встановлений першим
  dependsOn: []

---
# infrastructure/cert-manager/cert-manager.yaml
# Основний cert-manager HelmRelease з покращеним управлінням залежностями
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.18.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  # Чекаємо поки CRDs будуть встановлені та зареєстровані
  dependsOn:
    - name: cert-manager-crds
      namespace: cert-manager
  # Додаємо додатковий час для реєстрації CRDs
  timeout: 10m
  # Більше спроб у разі тимчасових помилок
  maxHistory: 10
  values:
    # CRDs вже встановлені окремо
    installCRDs: false
    # Налаштування для ingress-shim (автоматичне створення сертифікатів)
    ingressShim:
      defaultIssuerKind: "ClusterIssuer"
      defaultIssuerName: "letsencrypt-prod"
    # Додаткові налаштування для стабільності
    webhook:
      timeoutSeconds: 30