apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: plex-media-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: plex-helm
        namespace: flux-system
  values:
    image:
      tag: "latest"
    env:
      TZ: Europe/Kiev
    service:
      main:
        type: LoadBalancer
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-pvc
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
    nodeSelector:
      kubernetes.io/hostname: pi4-node-1