apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 5m0s
  chart:
    spec:
      chart: plex
      version: "2.8.1"
      sourceRef:
        kind: HelmRepository
        name: alekc-charts
        namespace: flux-system
  values:
    env:
      TZ: "Europe/Berlin"
    hostNetwork: true
    nodeSelector:
      kubernetes.io/hostname: server

    persistence:
      config:
        enabled: true
        isPvc: true
        # НЕ вказуємо existingClaim - нехай створить новий
        storageClass: ""  # default storage class
        size: 2Gi
        accessModes:
          - ReadWriteOnce
      
      data:
        enabled: true
        isPvc: false
        customVolume:
          hostPath:
            path: /mnt/hdd
            type: Directory