apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "4.11.3"
  interval: 1m
  timeout: 5m
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    strategy: Recreate
  values:
    nodeSelector:
      kubernetes.io/hostn
    
    controller:
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
