apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: false     # Namespace створено окремим манифестом
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      metrics:
        enabled: true
    speaker:
      metrics:
        enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7472"
    installCRDs: true
    # Відключаємо автоматичне створення IPAddressPool з Helm chart
    configInline: |
      address-pools:
      - name: main-pool
        protocol: layer2
        addresses:
        - 192.168.0.100-192.168.0.109
      - name: pihole-pool
        protocol: layer2
        addresses:
        - 192.168.0.110-192.168.0.110
