apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.18.2
  install:
    createNamespace: true
    # Додаємо додаткові налаштування для стабільного встановлення
    remediation:
      retries: 3
    timeout: 10m
  # Додаємо налаштування для upgrade процесу
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    # Увімкнення CRDs - це правильно для простого встановлення
    crds:
      enabled: true
    # Додаємо базові налаштування для ingress-shim
    ingressShim:
      defaultIssuerKind: "ClusterIssuer"
      defaultIssuerName: "letsencrypt-prod"
    webhook:
      # Збільшуємо timeout для webhook для стабільності
      timeoutSeconds: 30