apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: kube-state-metrics-auto-update
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux-bot@pi4.com
        name: Flux Image Update Bot
      messageTemplate: |
        🚀 Automated Image Update

        Updated images:
        {{range .Updated.Images}}
        - {{.Name}}: {{.}}
        {{end}}

        Updated files:
        {{range .Updated.Files}}
        - {{.Path}}
        {{end}}

        ---
        _Automated by FluxCD Image Update Automation_
    push:
      branch: master
  update:
    path: "./"
    strategy: Setters
