apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: vm
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "6.1.5"
  interval: 1m
  timeout: 5m
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Додаткові налаштування, якщо потрібно
  values:
    image:
      tag: "v2.16.0"
      imagePullPolicy: IfNotPresent
    nodeSelector:
      kubernetes.io/hostname: server
