apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: vm
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "5.27.0"
  interval: 1m
  timeout: 5m
  values:
    image:
      tag: "v2.16.0" # {"$imagepolicy": "flux-system:kube-state-metrics-policy:tag"}
    nodeSelector:
      kubernetes.io/hostname: server
