apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: vm
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "5.27.0" # {"$imagepolicy": "vm:kube-state-metrics"}
  interval: 1m
  timeout: 5m
  dependsOn:
    - name: prometheus-operator-crds
      namespace: vm
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    strategy: Recreate
  # Додаткові налаштування, якщо потрібно
  values:
    nodeSelector:
      kubernetes.io/hostname: server
