apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: ingress-alerts
  namespace: vm
spec:
  groups:
    - name: ingress.rules
      rules:
        - alert: IngressNotAvailable
          expr: probe_success == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Ingress {{ $labels.instance }} is not available"
            description: "Ingress {{ $labels.instance }} has been unavailable for more than 5 minutes"

        - alert: IngressSSLCertExpiringSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "SSL certificate for {{ $labels.instance }} is expiring soon"
            description: "SSL certificate will expire in less than 30 days"