apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: vm
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "9.4.4"
  interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Встановлення VictoriaMetrics плагіна
    env:
      GF_INSTALL_PLUGINS: victoriametrics-metrics-datasource

    persistence:
      enabled: true
      size: 5Gi

#    adminPassword: "admin"  # змініть на більш безпечний

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        kubernetes.io/tls-acme: "true"
      hosts:
        - grafana.vm.192.168.0.100.nip.io
      path: /
      pathType: Prefix
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.vm.192.168.0.100.nip.io

    nodeSelector:
      kubernetes.io/hostname: server  # відповідно до вашого VMCluster

    # Автоматичне налаштування VictoriaMetrics datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: victoriametrics-metrics-datasource
            access: proxy
            url: http://vmselect-dev.vm.svc.cluster.local:8481/select/0/prometheus
            isDefault: true
            editable: true

          # Альтернативний Prometheus-тип datasource (якщо VM плагін не працює)
          - name: VictoriaMetrics-Prometheus
            type: prometheus
            access: proxy
            url: http://vmselect-dev.vm.svc.cluster.local:8481/select/0/prometheus
            isDefault: false
            editable: true

    # Автоматичне додавання дашбордів
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'victoriametrics'
            orgId: 1
            folder: 'VictoriaMetrics'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/victoriametrics

#    dashboards:
#      ingress-nginx:
#        nginx-ingress:
#          gnetId: 9614
#          revision: 1
#          datasource: VictoriaMetrics
#      k3s:
#        k3s-monitoring:
#          gnetId: 12425
#          revision: 1
#          datasource: VictoriaMetrics
#      victoriametrics:
#        victoriametrics-cluster:
#          gnetId: 11176
#          revision: 18
#          datasource: VictoriaMetrics
#      certmanager:
#        cert-manager:
#          gnetId: 11001
#          revision: 1
#          datasource: VictoriaMetrics
#      fluxcd:
#        Flux2:
#          gnetId: 16714
#          revision: 1
#          datasource: VictoriaMetrics
#