apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m0s
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    # Налаштування DNS сервісу
    serviceDns:
      type: LoadBalancer
      port: 53
      # Видаляємо loadBalancerIP, використовуємо лише анотації
      annotations:
        metallb.io/loadBalancerIPs: "192.168.0.110"
        metallb.io/allow-shared-ip: "pihole-shared-ip"
      externalTrafficPolicy: Local
    
    # Налаштування веб інтерфейсу
    serviceWeb:
      type: LoadBalancer
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443
      annotations:
        metallb.io/loadBalancerIPs: "192.168.0.110"
        metallb.io/allow-shared-ip: "pihole-shared-ip"
      externalTrafficPolicy: Local
    
    # Налаштування DHCP сервісу (якщо потрібен)
    serviceDhcp:
      enabled: false  # Відключаємо DHCP для уникнення конфліктів
      type: LoadBalancer
      port: 67
      annotations:
        metallb.io/loadBalancerIPs: "192.168.0.110" 
        metallb.io/allow-shared-ip: "pihole-shared-ip"
      externalTrafficPolicy: Local
    
    timezone: "Europe/Berlin"
    hostNetwork: false
    dnsPolicy: "ClusterFirst"
    
    nodeSelector:
      kubernetes.io/hostname: server
    
    persistentVolumeClaim:
      enabled: true
      storageClass: ""
      size: 1Gi
      accessModes:
        - ReadWriteOnce
    
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    
    privileged: true
    
    admin:
      enabled: true
    
    doh:
      enabled: true
      pullPolicy: Always
      envVars:
        DOH_UPSTREAM: "https://1.1.1.1/dns-query"
