apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
  namespace: vm
spec:
  releaseName: victoria-metrics-operator
  chart:
    spec:
      chart: victoria-metrics-operator
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      version: "0.36.0" # {"$imagepolicy": "vm:victoria-metrics-operator"}
  interval: 1m
  timeout: 5m
  dependsOn:
    - name: prometheus-operator-crds
      namespace: vm
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    strategy: Recreate
  values:
    operator:
      enable_converter: true
      prometheus_converter_add_argocd_ignore_annotations: false
