apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-operator
  namespace: vm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-operator
      app.kubernetes.io/name: victoria-metrics-operator
  namespaceSelector:
    matchNames:
      - vm
  endpoints:
  - port: http