apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: vm
spec:
  releaseName: prometheus-operator-crds
  chart:
    spec:
      chart: prometheus-operator-crds
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "22.0.2"
  interval: 1m
  timeout: 10m
  # Автооновлення для dev середовища
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    nodeSelector:
      kubernetes.io/hostname: server
    
    # Налаштування для правильної обробки CRDs
    fullnameOverride: ""
    nameOverride: ""

    # Додаткові labels для кращої організації
    commonLabels:
      app.kubernetes.io/part-of: prometheus-stack
