---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metallb-controller-pod-scrape
  namespace: metallb-system
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app: metallb
      component: controller
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      honorLabels: true
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metallb-speaker-pod-scrape
  namespace: metallb-system
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app: metallb
      component: speaker
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
      honorLabels: true
