apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: metallb-controller-scrape
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb
      component: controller
  namespaceSelector:
    any: false
    matchNames:
      - metallb-system
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: metallb-speaker-scrape
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  namespaceSelector:
    any: false
    matchNames:
      - metallb-system
  endpoints:
    - port: monitoring
      path: /metrics
      interval: 30s