apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: k8sonlab
        namespace: flux-system
      version: "2.6.1"
  interval: 1m
  values:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    service:
      type: ClusterIP
      port: 1883
    config:
      mosquitto.conf: |-
        persistence true
        persistence_location /mosquitto/data/
        log_dest stdout
        listener 1883
        allow_anonymous true
