apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: k8sonlab
        namespace: flux-system
      version: "2.6.1"
  interval: 1m
  values:
#    replicaCount: 1
#    image:
#      repository: eclipse-mosquitto
      # tag: ""                 # опціонально, за замовчуванням буде appVersion з chart
#      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 1883
    ports:
      mqtt:
        port: 1883
        protocol: TCP
      websocket:
        port: 9090
        protocol: TCP
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: local-path
      mountPath: /mosquitto/data
    config: |
      persistence true
      persistence_location /mosquitto/data/
      log_dest stdout
      listener 1883
      allow_anonymous true
      listener 9090
      protocol websockets
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
