apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      sourceRef:
        kind: HelmRepository
        name: t3n-mosquitto
        namespace: flux-system
      version: "2.4.1"
  interval: 1m
  values:
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
    replicaCount: 1
    service:
      type: ClusterIP
      port: 1883
    config:
      allowAnonymous: true
      log:
        - stdout
      listener:
        - 1883
