apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: vm
spec:
  releaseName: node-exporter
  chart:
    spec:
      chart: prometheus-node-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "4.42.0"
  interval: 2m
  timeout: 5m
  # Додаткові налаштування, якщо потрібно
  values: {}
