apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
      version: "1.7.0"  # актуальна версія чарту (дивіться у repo)
  interval: 5m
  values:
    image:
      tag: 2025.7.4
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: NodePort
      port: 38123
    ingress:
      enabled: false
    extraVolumes:
      - name: bluetooth
        hostPath:
          path: /run/dbus
    #Bluetooth devices
    extraVolumeMounts:
      - name: bluetooth
        mountPath: /run/dbus
        # note that this is readonly to prevent security issues
        readOnly: true
