apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  targetNamespace: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
      version: "0.3.16"
  interval: 1m
  # Автооновлення для dev середовища
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hostNetwork: true
    image:
      tag: "2025.8.2"
      imagePullPolicy: IfNotPresent
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: ClusterIP
    ingress:
      enabled: false
    nodeSelector:
      kubernetes.io/hostname: pi4
    additionalVolumes:
      - name: dbus
        hostPath:
          path: /run/dbus
          type: Directory
    additionalMounts:
      - name: dbus
        mountPath: /run/dbus
        readOnly: true

#    additionalMounts:
#      - name: bluetooth
#        mountPath: /run/dbus
