apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
      version: "0.3.22"
  interval: 1m
  # Автооновлення для dev середовища
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    securityContext:
      privileged: true
    hostNetwork: false
    image:
      tag: "2025.9.4"
      imagePullPolicy: IfNotPresent
    persistence:
      enabled: true
      size: 5Gi
    service:
      type: LoadBalancer
      port: 8123
      annotations:
        metallb.io/loadBalancerIPs: "192.168.0.109"
    ingress:
      enabled: false
    nodeSelector:
      kubernetes.io/hostname: server
    additionalVolumes:
      - name: dbus
        hostPath:
          path: /run/dbus
          type: Directory
          
    additionalMounts:
      - name: dbus
        mountPath: /run/dbus
        readOnly: true


#    additionalMounts:
#      - name: bluetooth
#        mountPath: /run/dbus
